### ISSUE TITLE
F1 opens the help tab on chrome.

### ISSUE THREAD

**Issue by alexo310** [ibratabian17/KPoe#1]
So, the key we need to press to refresh the songlist is F1, however, on chrome, it opens the help tab. There's also no way to remove that shortcut. I think shift + r is a good replacement.

**Comment by ibratabian17** [comment]
I see, I see here the F1 button still does the keymap that Chrome does, and this problem can be fixed by adding ```event.preventDefault()``` in keymap.js, I will fix it

**Comment by ibratabian17** [comment]
the commit eacf1b083b1b915e3718aed9e377f418fd3f875a solved the issue
